name: Scrape

on:
  push:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Create virtual environment
      run: python -m venv env

    - name: Activate virtual environment
      run: source env/bin/activate

    - name: Install requirements
      run: pip install -r requirements.txt

    - name: Run scraper
      run: python3 scrape.py

    - name: Add and commit	
      run: |-	
        git add .	
        git config user.name "Automated"	
        git config user.email "actions@users.noreply.github.com"	
        git commit -m "Latest data" 	
    - name: Push	
      run: git push
